import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import SideNavBar from "@/components/SideNavBar";
import Link from "next/link";
import { FlaskConical } from "lucide-react";
import BorrowButton from "@/components/BorrowButton";
import { ApolloProvider } from "@apollo/client";
import client from "@/context/ApolloContext";
import { ApolloNextAppProvider } from "@apollo/experimental-nextjs-app-support";
import { makeClient } from "@/context/ApolloContext";
import ApolloWrapper from "@/context/ApolloWrapper";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const inter = Inter({
	subsets: ["latin"],
	display: "swap", // Recommended for better performance
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className} antialiased`}>
				<div className="flex items-stretch">
					<ApolloWrapper client={client}>{children}</ApolloWrapper>

					<div className="flex-1 relative h-full">
						<Link href="/borrow">
							<BorrowButton />
						</Link>
					</div>
				</div>
			</body>
		</html>
	);
}
