import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import SideNavBar from "@/components/SideNavBar";
import Link from "next/link";
import { FlaskConical } from "lucide-react";
import BorrowButton from "@/components/BorrowButton";
import ApolloWrapper from "@/context/ApolloWrapper";
import { ClerkProvider } from "@clerk/nextjs";
import LoginButton from "@/components/LoginButton";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const inter = Inter({
	subsets: ["latin"],
	display: "swap", // Recommended for better performance
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className} antialiased`}>
				<div className="flex items-stretch">
					<ClerkProvider>
						<ApolloWrapper>
							<SideNavBar />
							<div className="absolute top-0 right-0">
								<LoginButton />
							</div>

							{children}
						</ApolloWrapper>

						<div className="flex-1 relative h-full">
							<Link href="/borrow">
								<BorrowButton />
							</Link>
						</div>
					</ClerkProvider>
				</div>
			</body>
		</html>
	);
}
